services:
  db:
    image: mysql:8.0
    container_name: task1-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@123
      MYSQL_DATABASE: task1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  web:
    build: .
    container_name: task1-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: "mysql+pymysql://root:Mysql%40123@db:3306/task1"

volumes:
  mysql_data:
